project:
  type: website
  output-dir: docs

website:
  title: "Eshan Gujarathi"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
      - href: https://drive.google.com/file/d/1lQFYYaDovnqgM81TEpzJRC1mkko1j6sD/view?usp=sharing
        text: CV
      - href: blogs
        text: Blogs
      - href: achievements.qmd
        text: Achievements

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto

