project:
  type: website
  output-dir: docs

website:
  title: "Eshan Gujarathi"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: Teaching.qmd
        text: Teaching

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto

